package easy2;

/**
 * 389. Find the Difference
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */
public class FindtheDifference
{
    public char findTheDifference(String s, String t)
    {
        char c = 0;
        for(int i = 0; i < s.length(); i++)
        {
            c ^= s.charAt(i);
        }
        for(int j = 0; j < t.length(); j++)
        {
            c ^= t.charAt(j);
        }

        return c;
    }

    public static void main(String[] args)
    {
        System.out.println(new FindtheDifference().findTheDifference("a", "aa"));
    }
}
